package city.fini.ddsl.generator;

import city.fini.ddsl.ast.Ast;
import city.fini.ddsl.ast.Ast.*;
import city.fini.ddsl.diagnostics.DdslException;
import city.fini.ddsl.metadata.Metadata;
import city.fini.ddsl.model.Model;
import city.fini.ddsl.model.Model.*;
import java.util.List;
import java.util.stream.Collectors;

public final class DockerfileGenerator {
  private DockerfileGenerator() {}

  public static String generate(ProgramModel program) {
    StringBuilder out = new StringBuilder("# Generated by ddsl. Do not edit by hand.\n\n");
    for (int i = 0; i < program.stages().size(); i++) {
      StageModel stage = program.stages().get(i);
      if (i > 0) out.append('\n');
      out.append("FROM ").append(stage.base().image()).append(" AS ").append(stage.name()).append('\n');
      for (StageOp op : stage.statements()) {
        emitOp(out, stage, op);
      }
    }
    return out.toString();
  }

  private static void emitOp(StringBuilder out, StageModel stage, StageOp op) {
    if (op instanceof Model.Workdir workdir) {
      out.append("WORKDIR ").append(shellWord(workdir.path())).append('\n');
    } else if (op instanceof Model.User user) {
      out.append("USER ").append(shellWord(user.user())).append('\n');
    } else if (op instanceof Model.Update) {
      emitUpdate(out, stage.base().metadata().packageManager());
    } else if (op instanceof InstallTools install) {
      emitInstallTools(out, stage.base().distro(), stage.base().metadata().packageManager(), install.tools());
    } else if (op instanceof Model.CopyPaths copy) {
      out.append("COPY ")
          .append(copy.sources().stream().map(DockerfileGenerator::shellWord).collect(Collectors.joining(" ")))
          .append(' ')
          .append(shellWord(copy.dest()))
          .append('\n');
    } else if (op instanceof Model.CopyArtifact copy) {
      if (copy.targetName().isPresent()) {
        out.append("# copy artifact ")
            .append(copy.name())
            .append(" as target artifact ")
            .append(copy.targetName().get())
            .append(" from ")
            .append(copy.fromStage())
            .append(':')
            .append(shellWord(copy.sourcePath().raw()))
            .append(" to ")
            .append(shellWord(copy.dest()))
            .append('\n');
      } else {
        out.append("# copy artifact ")
            .append(copy.name())
            .append(" from ")
            .append(copy.fromStage())
            .append(':')
            .append(shellWord(copy.sourcePath().raw()))
            .append(" to ")
            .append(shellWord(copy.dest()))
            .append('\n');
      }
      out.append("COPY --from=")
          .append(copy.fromStage())
          .append(' ')
          .append(shellWord(copy.sourcePath().raw()))
          .append(' ')
          .append(shellWord(copy.dest()))
          .append('\n');
    } else if (op instanceof RunTool tool) {
      emitTool(out, tool, stage.statements());
    } else if (op instanceof ProduceArtifact artifact) {
      out.append("# produces artifact ")
          .append(artifact.name())
          .append(" at ")
          .append(shellWord(artifact.path().raw()))
          .append('\n');
    } else if (op instanceof Model.CarryTool carry) {
      List<String> paths = Metadata.carriedToolPaths(carry.name())
          .orElseThrow(() -> new DdslException("carried tool '" + carry.name() + "' has no filesystem path mapping", null));
      out.append("# carry tool ").append(carry.name()).append('\n');
      for (String path : paths) {
        out.append("COPY --from=").append(carry.fromStage()).append(' ').append(path).append(' ').append(path).append('\n');
      }
    } else if (op instanceof Model.Runtime runtime) {
      emitRuntime(out, runtime.config());
    } else if (op instanceof Model.Expose expose) {
      out.append("EXPOSE ").append(expose.port()).append('\n');
    }
  }

  private static void emitUpdate(StringBuilder out, PackageManager pm) {
    switch (pm) {
      case APK -> out.append("RUN apk update && apk upgrade --no-cache\n");
      case APT -> out.append("RUN apt-get update && apt-get upgrade -y && rm -rf /var/lib/apt/lists/*\n");
      case DNF -> out.append("RUN dnf upgrade -y && dnf clean all\n");
      case NONE -> throw new DdslException("update requires a package manager", null);
    }
  }

  private static void emitInstallTools(StringBuilder out, Ast.Distro distro, PackageManager pm, List<String> tools) {
    List<String> packages = tools.stream()
        .map(tool -> Metadata.packageForTool(tool, distro)
            .orElseThrow(() -> new DdslException("tool '" + tool + "' is not mapped for this distro", null)))
        .toList();
    switch (pm) {
      case APK -> out.append("RUN apk add --no-cache ").append(String.join(" ", packages)).append('\n');
      case APT -> out.append("RUN apt-get update && apt-get install -y --no-install-recommends ")
          .append(String.join(" ", packages))
          .append(" && rm -rf /var/lib/apt/lists/*\n");
      case DNF -> out.append("RUN dnf install -y ").append(String.join(" ", packages)).append(" && dnf clean all\n");
      case NONE -> throw new DdslException("tool installation requires a package manager", null);
    }
  }

  private static void emitTool(StringBuilder out, RunTool tool, List<StageOp> ops) {
    if (tool.config() instanceof GoTool go && go.build()) {
      ArtifactPath artifact = ops.stream()
          .filter(ProduceArtifact.class::isInstance)
          .map(ProduceArtifact.class::cast)
          .map(ProduceArtifact::path)
          .findFirst()
          .orElseThrow(() -> new DdslException("go build requires an artifact path to infer output", null));
      if (artifact.isPattern()) {
        throw new DdslException("go build output artifact must use an exact path, not a wildcard pattern", null);
      }
      out.append("RUN go build -o ").append(shellWord(artifact.raw())).append('\n');
    } else if (tool.config() instanceof MavenTool maven) {
      out.append("RUN mvn -B");
      for (String goal : maven.goals()) out.append(' ').append(goal);
      if (maven.skipTests()) out.append(" -DskipTests");
      out.append('\n');
    } else if (tool.config() instanceof PythonTool python) {
      out.append("RUN pip install --no-cache-dir -r ").append(shellWord(python.requirements())).append('\n');
    } else if (tool.config() instanceof NodeTool node && node.install() == NodeInstall.PROD) {
      out.append("RUN npm install --production\n");
    }
  }

  private static void emitRuntime(StringBuilder out, RuntimeConfig config) {
    if (config instanceof BinaryRuntime binary) {
      out.append("ENTRYPOINT [").append(jsonArgs(binary.entry())).append("]\n");
    } else if (config instanceof JavaRuntime java) {
      out.append("ENTRYPOINT [").append(jsonArgs("java", "-jar", java.jar())).append("]\n");
    } else if (config instanceof PythonRuntime python) {
      out.append("ENTRYPOINT [").append(jsonArgs("python", python.entry())).append("]\n");
    } else if (config instanceof NodeRuntime node) {
      out.append("ENTRYPOINT [").append(jsonArgs("node", node.entry())).append("]\n");
    }
  }

  private static String shellWord(String value) {
    return value.chars().allMatch(c -> Character.isLetterOrDigit(c) || c == '/' || c == '.' || c == '_' || c == '-' || c == '*')
        ? value
        : "\"" + value.replace("\\", "\\\\").replace("\"", "\\\"") + "\"";
  }

  private static String jsonArgs(String... args) {
    return java.util.Arrays.stream(args)
        .map(arg -> "\"" + arg.replace("\\", "\\\\").replace("\"", "\\\"") + "\"")
        .collect(Collectors.joining(","));
  }
}
