use crate::ast::{NodeInstall, RuntimeConfig, ToolConfig};
use crate::error::Diagnostic;
use crate::metadata::{carried_tool_paths, package_for_tool, PackageManager};
use crate::model::{ArtifactPath, ProgramModel, StageOp, ToolInvocation};

pub fn generate(program: &ProgramModel) -> Result<String, Diagnostic> {
    let mut out = String::new();
    out.push_str("# Generated by ddsl. Do not edit by hand.\n\n");

    for (stage_idx, stage) in program.stages.iter().enumerate() {
        if stage_idx > 0 {
            out.push('\n');
        }
        out.push_str(&format!("FROM {} AS {}\n", stage.base.image, stage.name));
        for op in &stage.statements {
            match op {
                StageOp::Workdir(path) => out.push_str(&format!("WORKDIR {}\n", shell_word(path))),
                StageOp::User(user) => out.push_str(&format!("USER {}\n", shell_word(user))),
                StageOp::Update => emit_update(&mut out, stage.base.metadata.package_manager)?,
                StageOp::InstallTools(tools) => emit_install_tools(
                    &mut out,
                    stage.base.distro,
                    stage.base.metadata.package_manager,
                    tools,
                )?,
                StageOp::CopyPaths { sources, dest } => {
                    let srcs = sources
                        .iter()
                        .map(|s| shell_word(s))
                        .collect::<Vec<_>>()
                        .join(" ");
                    out.push_str(&format!("COPY {} {}\n", srcs, shell_word(dest)));
                }
                StageOp::CopyArtifact {
                    name,
                    target_name,
                    from_stage,
                    source_path,
                    dest,
                } => {
                    if let Some(target_name) = target_name {
                        out.push_str(&format!(
                            "# copy artifact {} as target artifact {} from {}:{} to {}\n",
                            name,
                            target_name,
                            from_stage,
                            shell_word(&source_path.raw),
                            shell_word(dest)
                        ));
                    } else {
                        out.push_str(&format!(
                            "# copy artifact {} from {}:{} to {}\n",
                            name,
                            from_stage,
                            shell_word(&source_path.raw),
                            shell_word(dest)
                        ));
                    }
                    out.push_str(&format!(
                        "COPY --from={} {} {}\n",
                        from_stage,
                        shell_word(&source_path.raw),
                        shell_word(dest)
                    ));
                }
                StageOp::RunTool(invocation) => emit_tool(&mut out, invocation, &stage.statements)?,
                StageOp::ProduceArtifact { name, path } => {
                    out.push_str(&format!(
                        "# produces artifact {} at {}\n",
                        name,
                        shell_word(&path.raw)
                    ));
                }
                StageOp::CarryTool { name, from_stage } => {
                    let paths = carried_tool_paths(name).ok_or_else(|| {
                        Diagnostic::new(
                            format!("carried tool '{name}' has no filesystem path mapping"),
                            None,
                        )
                    })?;
                    out.push_str(&format!("# carry tool {}\n", name));
                    for path in paths {
                        out.push_str(&format!("COPY --from={} {} {}\n", from_stage, path, path));
                    }
                }
                StageOp::Runtime(runtime) => emit_runtime(&mut out, &runtime.config),
                StageOp::Expose(port) => out.push_str(&format!("EXPOSE {}\n", port)),
            }
        }
    }

    Ok(out)
}

fn emit_update(out: &mut String, pm: PackageManager) -> Result<(), Diagnostic> {
    match pm {
        PackageManager::Apk => out.push_str("RUN apk update && apk upgrade --no-cache\n"),
        PackageManager::Apt => out
            .push_str("RUN apt-get update && apt-get upgrade -y && rm -rf /var/lib/apt/lists/*\n"),
        PackageManager::Dnf => out.push_str("RUN dnf upgrade -y && dnf clean all\n"),
        PackageManager::None => {
            return Err(Diagnostic::new("update requires a package manager", None))
        }
    }
    Ok(())
}

fn emit_install_tools(
    out: &mut String,
    distro: crate::ast::Distro,
    pm: PackageManager,
    tools: &[String],
) -> Result<(), Diagnostic> {
    let packages = tools
        .iter()
        .map(|tool| {
            package_for_tool(tool, distro).ok_or_else(|| {
                Diagnostic::new(format!("tool '{tool}' is not mapped for this distro"), None)
            })
        })
        .collect::<Result<Vec<_>, _>>()?;
    match pm {
        PackageManager::Apk => out.push_str(&format!("RUN apk add --no-cache {}\n", packages.join(" "))),
        PackageManager::Apt => out.push_str(&format!("RUN apt-get update && apt-get install -y --no-install-recommends {} && rm -rf /var/lib/apt/lists/*\n", packages.join(" "))),
        PackageManager::Dnf => out.push_str(&format!("RUN dnf install -y {} && dnf clean all\n", packages.join(" "))),
        PackageManager::None => return Err(Diagnostic::new("tool installation requires a package manager", None)),
    }
    Ok(())
}

fn emit_tool(
    out: &mut String,
    invocation: &ToolInvocation,
    stage_ops: &[StageOp],
) -> Result<(), Diagnostic> {
    match &invocation.config {
        ToolConfig::Go { build } => {
            if *build {
                let artifact = find_stage_artifact(stage_ops).ok_or_else(|| {
                    Diagnostic::new("go build requires an artifact path to infer output", None)
                })?;
                if artifact.is_pattern() {
                    return Err(Diagnostic::new(
                        "go build output artifact must use an exact path, not a wildcard pattern",
                        None,
                    ));
                }
                out.push_str(&format!("RUN go build -o {}\n", shell_word(&artifact.raw)));
            }
        }
        ToolConfig::Maven { goals, skip_tests } => {
            let mut args = vec!["mvn".to_string(), "-B".to_string()];
            args.extend(goals.iter().cloned());
            if *skip_tests {
                args.push("-DskipTests".to_string());
            }
            out.push_str(&format!("RUN {}\n", args.join(" ")));
        }
        ToolConfig::Python { requirements } => {
            out.push_str(&format!(
                "RUN pip install --no-cache-dir -r {}\n",
                shell_word(requirements)
            ));
        }
        ToolConfig::Node { install } => match install {
            NodeInstall::Prod => out.push_str("RUN npm install --production\n"),
        },
    }
    Ok(())
}

fn find_stage_artifact(stage_ops: &[StageOp]) -> Option<&ArtifactPath> {
    stage_ops.iter().find_map(|op| match op {
        StageOp::ProduceArtifact { path, .. } => Some(path),
        _ => None,
    })
}

fn emit_runtime(out: &mut String, runtime: &RuntimeConfig) {
    match runtime {
        RuntimeConfig::Binary { entry } => {
            out.push_str(&format!("ENTRYPOINT [{}]\n", json_args(&[entry])))
        }
        RuntimeConfig::Java { jar } => out.push_str(&format!(
            "ENTRYPOINT [{}]\n",
            json_args(&["java", "-jar", jar])
        )),
        RuntimeConfig::Python { entry } => {
            out.push_str(&format!("ENTRYPOINT [{}]\n", json_args(&["python", entry])))
        }
        RuntimeConfig::Node { entry } => {
            out.push_str(&format!("ENTRYPOINT [{}]\n", json_args(&["node", entry])))
        }
    }
}

fn shell_word(value: &str) -> String {
    if value
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || matches!(c, '/' | '.' | '_' | '-' | '*'))
    {
        value.to_string()
    } else {
        format!("{value:?}")
    }
}

fn json_args(args: &[&str]) -> String {
    args.iter()
        .map(|arg| format!("{arg:?}"))
        .collect::<Vec<_>>()
        .join(",")
}
